version: '3.8'

services:
  globepilot:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      # Optional: Mount logs directory
      - ./logs:/app/logs
    networks:
      - globepilot-network

networks:
  globepilot-network:
    driver: bridge 